import * as THREE from 'three';
import { World, polygons } from './world';
import { cities, positions } from './data';
import { demoWeather, fetchWeather, weatherName } from './weather.mjs';
import { stepFlight, damp } from './flight.mjs';
import './style.css';
const icons:Record<string,string>={plane:'<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',play:'<path d="m8 5 11 7-11 7Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5Z"/>',camera:'<path d="M5 7h3l2-3h4l2 3h3a2 2 0 0 1 2 2v10H3V9a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="3"/>',volume:'<path d="m11 5-5 4H3v6h3l5 4Zm4 3a5 5 0 0 1 0 8m3-11a9 9 0 0 1 0 14"/>',mute:'<path d="m11 5-5 4H3v6h3l5 4Zm5 4 5 6m0-6-5 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',view:'<path d="M3 9V3h6m6 0h6v6m0 6v6h-6m-6 0H3v-6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',cloud:'<path d="M6 19a5 5 0 1 1 0-10 7 7 0 0 1 13-1 5 5 0 0 1 0 11Z"/>'};
function icon(name:string){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.plane}</svg>`;}
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<canvas id="scene" aria-label="대한민국의 도시와 해안을 비행하는 3D 세계"></canvas><div id="shade"></div><div id="loading"><div class="spinner"></div><strong>바람결</strong><p id="loading-text">당신을 위한 하늘을 준비하고 있어요.</p></div>
<header class="topbar"><div class="brand"><span class="brand-mark">${icon('plane')}</span><div><strong>바람결</strong><small>KOREA SKY JOURNEY</small></div></div><div class="top-right"><button class="weather-card" id="weather-button" aria-label="날씨 설정 열기"><span class="weather-icon">${icon('sun')}</span><div><strong id="weather-title">서울 · 날씨 불러오는 중</strong><small><span class="live-dot"></span><span id="weather-status">현재 날씨 연결 중</span></small></div></button><button class="icon-button" id="settings-button" aria-label="여행 설정">${icon('settings')}</button></div></header>
<div class="destination"><div class="region"><span class="location-icon"></span><span id="region">서울의 하늘</span></div><h2 id="city-title">서울, 한강 위에서</h2><p id="city-description">한강을 따라 흐르는 도시의 아침</p></div>
<section class="intro" id="intro"><div class="intro-kicker">서두르지 않아도 괜찮아요</div><h1>마음이 가는 곳으로,<br>바람이 부는 대로.</h1><p>서울의 아침에서 동해의 수평선까지.<br>구름 사이로 떠나는 작은 한국 여행.</p><button class="primary" id="start">하늘 여행 시작 ${icon('arrow')}</button><small>자동 여행으로 편안하게 · 언제든 직접 조종</small></section>
<div class="altitude-rail"><input id="altitude" type="range" min="100" max="3000" step="10" value="380" aria-label="목표 비행 고도"><div class="altitude-labels"><span>구름 위</span><span>비행 고도</span><span>도시 가까이</span></div></div>
<aside class="map-card"><div class="map-title"><span>우리의 비행 경로</span><span id="visited-count">0 / 10</span></div><canvas id="map" width="424" height="462" aria-label="서울에서 한국의 서해 남해 동해를 잇는 비행 지도"></canvas><button class="map-footer" id="destinations-button">다른 도시로 떠나기 ${icon('arrow')}</button></aside>
<div id="landmark" class="landmark-label"></div><div class="bottom"><div class="instrument"><small>고도</small><strong id="height">380</strong><em>m</em></div><div class="instrument"><small>속도</small><strong id="speed">0</strong><em>km/h</em></div><button class="mode-button active" id="mode" aria-pressed="true">${icon('compass')}<span>자동 여행</span></button><div class="divider"></div><button class="control-button" id="pause" aria-label="일시정지">${icon('pause')}</button><button class="control-button" id="view" aria-label="시점 변경">${icon('view')}</button><button class="control-button photo-btn" id="cinema" aria-label="풍경만 보기">${icon('camera')}</button><button class="control-button" id="sound" aria-label="자연 소리 켜기">${icon('mute')}</button></div>
<div class="touch-controls"><button data-key="ArrowLeft" aria-label="왼쪽 선회">←</button><button data-key="ArrowRight" aria-label="오른쪽 선회">→</button><button data-key="ArrowUp" class="updown" aria-label="상승">↑</button><button data-key="ArrowDown" aria-label="하강">↓</button></div><div class="keys-hint"><kbd>←</kbd> <kbd>→</kbd> 선회 &nbsp; <kbd>↑</kbd> <kbd>↓</kbd> 상승·하강<br><kbd>Space</kbd> 빠르게 &nbsp; <kbd>C</kbd> 시점 &nbsp; <kbd>P</kbd> 쉼</div><div class="credits">상상으로 다듬은 한국 · <a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">날씨 Open-Meteo</a> · <a href="https://www.naturalearthdata.com/" target="_blank" rel="noopener noreferrer">지도 Natural Earth</a></div>
<section class="drawer" id="destinations" hidden><div class="drawer-head"><h2>어디로 떠나볼까요?</h2><button class="control-button" data-close aria-label="닫기">${icon('close')}</button></div><p>가까이 다가가면 여행 도장이 남아요.<br>도시를 고르면 그곳의 하늘로 이동합니다.</p><div id="city-list"></div></section>
<section class="drawer" id="settings" hidden><div class="drawer-head"><h2>나만의 하늘</h2><button class="control-button" data-close aria-label="닫기">${icon('close')}</button></div><label class="field"><span>날씨</span><select id="weather-mode"><option value="live">도시의 현재 날씨</option><option value="clear">맑은 날</option><option value="cloudy">구름 가득한 날</option><option value="rain">비 오는 날</option><option value="sunset">노을 진 하늘</option></select></label><label class="field"><span>화면 품질</span><select id="quality"><option value="high">선명하게</option><option value="low">가볍게</option></select></label><div class="weather-details" id="weather-details">현재 날씨를 확인하고 있어요.</div><button class="small-action" id="refresh-weather">날씨 새로고침</button><p>실제 도시의 구름량·풍속·풍향을 풍경에 반영합니다. 지상 관측 날씨를 활용한 연출로, 실제 비행 정보가 아닙니다.</p><p>지형과 관광지는 여행의 분위기를 살린 축약 모형입니다. 개인정보나 위치 권한은 필요하지 않아요.</p></section>
<div class="paused-badge" id="paused" hidden><strong>잠시, 숨을 고르세요.</strong><p>풍경은 여기서 기다리고 있어요.</p><button class="primary" id="resume">이어서 여행 ${icon('play')}</button></div><div class="toast" id="toast" role="status" hidden></div><button class="cinema-exit" id="cinema-exit">화면 돌아오기 · H</button>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let renderer:THREE.WebGLRenderer;
try{renderer=new THREE.WebGLRenderer({canvas:$<HTMLCanvasElement>('scene'),antialias:true,powerPreference:'high-performance'});}catch{$('loading-text').textContent='3D 화면을 열 수 없어요. WebGL을 지원하는 최신 브라우저에서 다시 열어주세요.';throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const world=new World(),camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,1,100000);const planePosition=new THREE.Vector3();
const state={x:positions[0].x,y:380,z:positions[0].z+650,heading:0,bank:0,pitch:0,speed:85};
let started=false,paused=false,auto=true,current=0,target=1,view=0,elapsed=0,lastTime=0,lastHUD=0,targetAltitude=380,weatherMode='live',weatherList=Array.from({length:cities.length},()=>({...demoWeather})),refreshing=false,lastFetch=0,soundOn=false,tourComplete=false,toastTimer=0;
const keys=new Set<string>(),visited=new Set<number>();try{const stored=JSON.parse(localStorage.getItem('baramgyeol-visits-v1')||'[]');if(Array.isArray(stored))stored.filter(n=>Number.isInteger(n)&&n>=0&&n<cities.length).forEach(n=>visited.add(n));}catch{/* Storage is optional. */}
const map=$<HTMLCanvasElement>('map'),mapCtx=map.getContext('2d')!;
const weather=()=>weatherMode==='live'?weatherList[current]:{...demoWeather,cloud:weatherMode==='cloudy'?91:weatherMode==='rain'?96:22,code:weatherMode==='rain'?63:weatherMode==='cloudy'?3:1,wind:weatherMode==='rain'?24:9,day:true};
function toast(text:string){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>$('toast').hidden=true,3700);}
function remember(i:number){if(visited.has(i))return;visited.add(i);try{localStorage.setItem('baramgyeol-visits-v1',JSON.stringify([...visited]));}catch{}renderCities();if(started)toast(`${cities[i].name}의 하늘을 만났어요. 여행 도장 ${visited.size} / 10`);}
function renderCities(){$('city-list').replaceChildren();cities.forEach((c,i)=>{const b=document.createElement('button');b.className='city-button'+(i===current?' current':'');b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')}</span><div><strong>${c.name}</strong><small>${c.region} · ${c.landmark}</small></div><span class="stamp">${visited.has(i)?'✓':'○'}</span>`;b.onclick=()=>travel(i);$('city-list').append(b);});$('visited-count').textContent=`${visited.size} / 10`;}
function setCity(i:number){current=i;$('region').textContent=cities[i].region;$('city-title').textContent=i===0?'서울, 한강 위에서':`${cities[i].name}의 하늘`;$('city-description').textContent=cities[i].desc;renderCities();updateWeatherHUD();}
function closeDrawers(){$('settings').hidden=true;$('destinations').hidden=true;}
function travel(i:number){setCity(i);state.x=positions[i].x;state.z=positions[i].z+650;state.y=Math.max(380,world.ground(state.x,state.z)+130);targetAltitude=state.y;$<HTMLInputElement>('altitude').value=String(targetAltitude);state.heading=0;state.bank=0;state.pitch=0;target=(i+1)%cities.length;tourComplete=false;closeDrawers();if(!started)begin();snapCamera();toast(`${cities[i].name}에 도착했어요. ${cities[i].landmark}을 찾아보세요.`);}
function begin(){started=true;paused=false;document.body.classList.add('started');$('intro').hidden=true;$('paused').hidden=true;remember(current);toast('지금은 자동 여행 중이에요. 방향키를 누르면 직접 조종합니다.');}
function toggleAuto(){auto=!auto;$('mode').classList.toggle('active',auto);$('mode').setAttribute('aria-pressed',String(auto));$('mode').innerHTML=icon('compass')+`<span>${auto?'자동 여행':'직접 조종'}</span>`;if(auto){target=(current+1)%cities.length;targetAltitude=state.y;}toast(auto?'바람에 몸을 맡겨보세요.':'방향키로 자유롭게 날아보세요.');}
function togglePause(){if(!started)return;paused=!paused;keys.clear();$('paused').hidden=!paused;$('pause').innerHTML=icon(paused?'play':'pause');$('pause').setAttribute('aria-label',paused?'여행 재개':'일시정지');}
function nextView(){view=(view+1)%3;toast(['비행기를 따라가는 시점','내 눈으로 바라보는 시점','주위를 둘러보는 시점'][view]);}
function updateWeatherHUD(){const w=weather(),name=weatherMode==='sunset'?'노을':weatherName(w.code);$('weather-title').textContent=`${cities[current].name} · ${name} ${Math.round(w.temperature)}°`;$('weather-status').textContent=weatherMode==='live'&&w.live?`현재 날씨 · 바람 ${Math.round(w.wind)} km/h`:weatherMode==='live'?'연결 대기 · 체험 날씨':'내가 고른 체험 날씨';const direction=['북','북동','동','남동','남','남서','서','북서'][Math.round(w.direction/45)%8];$('weather-details').textContent=`${cities[current].name} · ${name}\n구름량 ${w.cloud}% · ${direction}풍 ${w.wind.toFixed(1)} km/h${w.live?' · 관측 '+w.time.slice(11,16)+' (한국 시간)':' · 실제 관측값이 아닌 체험 날씨'}`;document.querySelector('.weather-icon')!.innerHTML=icon(w.cloud>50?'cloud':'sun');}
async function refreshWeather(){if(refreshing||Date.now()-lastFetch<60000)return;refreshing=true;lastFetch=Date.now();const button=$<HTMLButtonElement>('refresh-weather');button.disabled=true;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),10000);try{weatherList=await fetchWeather(cities,abort.signal);}catch{weatherList=weatherList.map(w=>({...w,live:false}));toast('현재 날씨 연결이 어려워 체험 날씨로 여행합니다.');}finally{clearTimeout(timer);refreshing=false;button.disabled=false;updateWeatherHUD();}}
$('start').onclick=begin;$('mode').onclick=()=>{if(!started)begin();toggleAuto();};$('pause').onclick=togglePause;$('resume').onclick=togglePause;$('view').onclick=nextView;
$('destinations-button').onclick=()=>{const open=$('destinations').hidden;closeDrawers();$('destinations').hidden=!open;};
for(const id of ['weather-button','settings-button'])$(id).onclick=()=>{const open=$('settings').hidden;closeDrawers();$('settings').hidden=!open;};document.querySelectorAll<HTMLElement>('[data-close]').forEach(b=>b.onclick=closeDrawers);
$<HTMLSelectElement>('weather-mode').onchange=e=>{weatherMode=(e.target as HTMLSelectElement).value;updateWeatherHUD();};
$('refresh-weather').onclick=()=>{if(Date.now()-lastFetch<60000)toast('날씨는 1분 뒤 다시 확인할 수 있어요.');else void refreshWeather();};
$<HTMLSelectElement>('quality').onchange=e=>{renderer.setPixelRatio((e.target as HTMLSelectElement).value==='low'?1:Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);};
$<HTMLInputElement>('altitude').oninput=e=>{targetAltitude=Number((e.target as HTMLInputElement).value);};
for(const id of ['cinema','cinema-exit'])$(id).onclick=()=>document.body.classList.toggle('hide-ui');
let audio:AudioContext|undefined,gain:GainNode|undefined;
$('sound').onclick=()=>{soundOn=!soundOn;if(!audio){audio=new AudioContext();gain=audio.createGain();gain.gain.value=0;gain.connect(audio.destination);const buffer=audio.createBuffer(1,audio.sampleRate*3,audio.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+Math.random()*.035-.0175)/1.02;data[i]=last*4;}const noise=audio.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;noise.connect(filter);filter.connect(gain);noise.start();}void audio.resume();$('sound').innerHTML=icon(soundOn?'volume':'mute');$('sound').setAttribute('aria-label',soundOn?'자연 소리 끄기':'자연 소리 켜기');};
window.addEventListener('keydown',e=>{if((e.target as HTMLElement).closest('input,select,button'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);if(!started)begin();if(auto&&e.key!==' ')toggleAuto();}if(!e.repeat){if(e.key.toLowerCase()==='p')togglePause();if(e.key.toLowerCase()==='c')nextView();if(e.key.toLowerCase()==='h')document.body.classList.toggle('hide-ui');if(e.key==='Escape'){closeDrawers();document.body.classList.remove('hide-ui');}}});window.addEventListener('keyup',e=>keys.delete(e.key));
const clearKeys=()=>{keys.clear();if(started&&!paused)togglePause();};window.addEventListener('blur',clearKeys);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearKeys();});
document.querySelectorAll<HTMLButtonElement>('[data-key]').forEach(button=>{button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);keys.add(button.dataset.key!);if(!started)begin();if(auto)toggleAuto();};const release=()=>keys.delete(button.dataset.key!);button.onpointerup=release;button.onpointercancel=release;button.onlostpointercapture=release;});
// Release button focus so keyboard flight controls remain available after a click.
document.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>b.blur()));
function drawMap(){const ctx=mapCtx;ctx.clearRect(0,0,424,462);const point=(x:number,z:number)=>({x:210+x*.025,y:150+z*.025});ctx.fillStyle='#d7e3de';ctx.strokeStyle='#bacdc5';ctx.lineWidth=.8;for(const p of polygons){ctx.beginPath();p.forEach((a,i)=>{const b=point(a[0],a[1]);if(i===0)ctx.moveTo(b.x,b.y);else ctx.lineTo(b.x,b.y);});ctx.closePath();ctx.fill();ctx.stroke();}ctx.setLineDash([4,5]);ctx.strokeStyle='#90aaa6';ctx.lineWidth=1.4;ctx.beginPath();positions.forEach((p,i)=>{const a=point(p.x,p.z);if(i===0)ctx.moveTo(a.x,a.y);else ctx.lineTo(a.x,a.y);});ctx.stroke();ctx.setLineDash([]);positions.forEach((p,i)=>{const a=point(p.x,p.z);ctx.beginPath();ctx.arc(a.x,a.y,i===current?5:3,0,Math.PI*2);ctx.fillStyle=visited.has(i)?'#307e76':'#a3b8b0';ctx.fill();if([0,1,3,4,6,8,9].includes(i)){ctx.fillStyle='#55787a';ctx.font='18px Arial';ctx.textAlign=i<4?'right':'left';ctx.fillText(cities[i].name,a.x+(i<4?-9:9),a.y+5);}});const p=point(state.x,state.z);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-state.heading);ctx.fillStyle='#bc8947';ctx.strokeStyle='#f7f4e7';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(7,8);ctx.lineTo(0,4);ctx.lineTo(-7,8);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
function snapCamera(){camera.position.set(state.x+180,state.y+100,state.z+280);camera.lookAt(state.x,state.y,state.z);}
snapCamera();renderCities();void refreshWeather();setInterval(()=>{if(!document.hidden)void refreshWeather();},10*60*1000);
function tick(now:number){const dt=Math.min((now-lastTime)/1000||0,.05);lastTime=now;if(!paused)elapsed+=dt;let w=weather();if(started&&!paused){if(auto){const dest=positions[target];const dx=dest.x-state.x,dz=dest.z-state.z;const desired=Math.atan2(-dx,-dz);let difference=THREE.MathUtils.euclideanModulo(desired-state.heading+Math.PI,Math.PI*2)-Math.PI;state.heading+=Math.max(-.5*dt,Math.min(.5*dt,difference));state.bank=damp(state.bank,-difference*.18,2,dt);state.speed=damp(state.speed,keys.has(' ')?200:90,1,dt);state.x-=Math.sin(state.heading)*state.speed*dt;state.z-=Math.cos(state.heading)*state.speed*dt;state.x-=Math.sin(w.direction*Math.PI/180)*Math.min(w.wind/3.6,12)*dt;state.z+=Math.cos(w.direction*Math.PI/180)*Math.min(w.wind/3.6,12)*dt;state.y=damp(state.y,Math.max(targetAltitude,world.ground(state.x,state.z)+155),1.5,dt);state.pitch=damp(state.pitch,0,2,dt);if(Math.hypot(dx,dz)<450){remember(target);setCity(target);target=(target+1)%cities.length;if(target===0&&!tourComplete){tourComplete=true;toast('한국의 세 바다를 모두 여행했어요. 하늘 여행은 계속됩니다.');}}}else{stepFlight(state,{turn:Number(keys.has('ArrowRight')||keys.has('d'))-Number(keys.has('ArrowLeft')||keys.has('a')),climb:Number(keys.has('ArrowUp')||keys.has('w'))-Number(keys.has('ArrowDown')||keys.has('s')),fast:keys.has(' ')},dt,w,(x:number,z:number)=>world.ground(x,z));if(keys.has('ArrowUp')||keys.has('ArrowDown')||keys.has('w')||keys.has('s')){targetAltitude=state.y;$<HTMLInputElement>('altitude').value=String(state.y);}else state.y=damp(state.y,Math.max(targetAltitude,world.ground(state.x,state.z)+60),1.6,dt);}
 let nearest=current,nearestD=Infinity;positions.forEach((p,i)=>{const d=Math.hypot(p.x-state.x,p.z-state.z);if(d<nearestD){nearest=i;nearestD=d;}if(d<650)remember(i);});if(nearest!==current)setCity(nearest);
 }
 if(!started){state.x=positions[0].x+Math.sin(elapsed*.035)*120;state.z=positions[0].z+650;state.y=380;state.heading=-.2;}
 planePosition.set(state.x,state.y+Math.sin(elapsed*.8)*1.4,state.z);world.aircraft.position.copy(planePosition);world.aircraft.rotation.set(state.pitch,state.heading,state.bank,'YXZ');world.aircraft.visible=view!==1;
 const forward=new THREE.Vector3(-Math.sin(state.heading),0,-Math.cos(state.heading)),desired=new THREE.Vector3(),look=new THREE.Vector3();
 if(!started){desired.copy(planePosition).add(new THREE.Vector3(150,100,260));look.set(positions[0].x+100,105,positions[0].z-150);}else if(view===0){desired.copy(planePosition).addScaledVector(forward,-145).add(new THREE.Vector3(0,48,0));look.copy(planePosition).addScaledVector(forward,160);}else if(view===1){desired.copy(planePosition).add(new THREE.Vector3(0,4,0));look.copy(planePosition).addScaledVector(forward,280).add(new THREE.Vector3(0,state.pitch*150,0));}else{desired.copy(planePosition).add(new THREE.Vector3(Math.cos(elapsed*.09)*230,115,Math.sin(elapsed*.09)*230));look.copy(planePosition);}
 camera.position.lerp(desired,1-Math.exp(-dt*3));camera.lookAt(look);world.update(paused?0:dt,w,planePosition);
 if(weatherMode==='sunset'){world.sky.material.uniforms.sunPosition.value.set(-.7,.045,-.7);world.sky.material.uniforms.turbidity.value=8;world.sun.color.set('#ffc896');(world.scene.fog as THREE.FogExp2).color.lerp(new THREE.Color('#dabaa6'),dt*2);}else world.sun.color.set('#fff1d4');
 renderer.render(world.scene,camera);
 if(now-lastHUD>150){$('height').textContent=Math.round(state.y).toLocaleString('ko');$('speed').textContent=started?String(Math.round(state.speed*3.6)):'0';drawMap();const landmark=world.landmarks[current],point=landmark.position.clone().add(new THREE.Vector3(0,current===0?240:80,0)),distance=point.distanceTo(planePosition);point.project(camera);const visible=point.z<1&&Math.abs(point.x)<.9&&Math.abs(point.y)<.7&&distance<2500;$('landmark').hidden=!visible;if(visible){$('landmark').textContent=cities[current].landmark;$('landmark').style.left=`${(point.x*.5+.5)*innerWidth}px`;$('landmark').style.top=`${(-point.y*.5+.5)*innerHeight}px`;}lastHUD=now;}
 if(gain&&audio)gain.gain.setTargetAtTime(soundOn&&!paused?.09:0,audio.currentTime,.4);requestAnimationFrame(tick);
}
world.ready.then(()=>{$('loading').hidden=true;requestAnimationFrame(tick);}).catch(error=>{console.error(error);$('loading-text').textContent='여행 풍경을 불러오지 못했어요. 페이지를 새로고침해 주세요.';});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();paused=true;$('loading').hidden=false;$('loading-text').textContent='3D 화면이 잠시 중단됐어요. 새로고침하면 여행을 이어갈 수 있어요.';});
