import * as THREE from 'three';
import { Sky } from 'three/addons/objects/Sky.js';
import { CloudField } from './clouds';
import { mergeVertices } from 'three/addons/utils/BufferGeometryUtils.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import boundaries from './korea.json';
import { cities, geo, positions } from './data';
export const polygons:number[][][]=boundaries.features.flatMap(f=>f.geometry.coordinates.map(p=>p[0].map(([lon,lat])=>{const a=geo(lon,lat);return [a.x,a.z];})));
function contains(x:number,z:number,poly:number[][]){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
const boxes=polygons.map(p=>({p,minX:Math.min(...p.map(a=>a[0])),maxX:Math.max(...p.map(a=>a[0])),minZ:Math.min(...p.map(a=>a[1])),maxZ:Math.max(...p.map(a=>a[1]))}));
export function isLand(x:number,z:number){return boxes.some(b=>x>=b.minX&&x<=b.maxX&&z>=b.minZ&&z<=b.maxZ&&contains(x,z,b.p));}
const peaks=[[128.465,38.118,850,600],[128.55,37.45,550,700],[128.1,36.8,620,680],[127.7,35.34,700,700],[127.08,37.9,390,520],[126.97,37.55,100,130],[126.53,33.36,680,700]].map(([a,b,h,r])=>({...geo(a,b),h,r}));
export function terrainHeight(x:number,z:number){if(!isLand(x,z))return 0;let h=17+12*Math.sin(x*.002)*Math.cos(z*.003);for(const p of peaks)h+=p.h*Math.exp(-((x-p.x)**2+(z-p.z)**2)/(p.r*p.r));h+=Math.max(0,Math.sin(x*.004+z*.001)*Math.cos(z*.003))*34;for(const c of positions){const d=Math.hypot(x-c.x,z-c.z);if(d<430)h=THREE.MathUtils.lerp(24,h,THREE.MathUtils.smoothstep(d,230,430));}return h;}
function rng(seed:number){return()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return(seed>>>0)/4294967296;};}
export class World{
 scene=new THREE.Scene();sky=new Sky();sun=new THREE.DirectionalLight('#fff1d4',2.3);hemi=new THREE.HemisphereLight('#c8e8ff','#7c9c72',2.4);ocean:THREE.Mesh;clouds=new CloudField();aircraft=new THREE.Group();landmarks:THREE.Group[]=[];obstacles:{x:number;z:number;w:number;d:number;h:number}[]=[];rain:THREE.LineSegments;snow:THREE.Points;stars:THREE.Points;moon:THREE.Mesh;private cityMaterial:THREE.MeshLambertMaterial|undefined;ready:Promise<void>;cameraCity=0;private time=0;private fogBase=.000095;
 constructor(){
  this.scene.fog=new THREE.FogExp2('#aacdda',.000095);this.scene.add(this.hemi,this.sun);this.sun.position.set(-4000,8000,-3000);this.sky.scale.setScalar(180000);this.scene.add(this.sky);this.sky.material.uniforms.turbidity.value=3;this.sky.material.uniforms.rayleigh.value=1.4;this.sky.material.uniforms.mieCoefficient.value=.003;this.sky.material.uniforms.mieDirectionalG.value=.8;
  const waterMaterial=new THREE.ShaderMaterial({uniforms:{time:{value:0},color:{value:new THREE.Color('#4d9fae')},light:{value:1},haze:{value:new THREE.Color('#aed1df')}},vertexShader:`varying vec3 vPosition; varying float vDepth; uniform float time; void main(){vec3 p=position; p.z+=sin(p.x*.012+time*.5)*1.3+sin(p.y*.015+time*.3)*1.2;vPosition=p;vec4 mv=modelViewMatrix*vec4(p,1.);vDepth=-mv.z;gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying vec3 vPosition;varying float vDepth;uniform vec3 haze;uniform float time;uniform vec3 color;uniform float light;void main(){float waves=sin(vPosition.x*.04+sin(vPosition.y*.022+time)*2.)*sin(vPosition.y*.05-time*.4);float glint=pow(max(0.,waves),16.)*.16;vec3 c=color+(waves*.018+glint);gl_FragColor=vec4(mix(c*light,haze,smoothstep(2500.,16000.,vDepth)),1.);}`});
  this.ocean=new THREE.Mesh(new THREE.PlaneGeometry(120000,120000,140,140),waterMaterial);this.ocean.rotation.x=-Math.PI/2;this.ocean.position.y=-2;this.scene.add(this.ocean);this.createTerrain();this.createCities();this.createTrees();this.createLandmarks();
  const random=rng(129);this.scene.add(this.clouds.group);
  const rainG=new THREE.BufferGeometry(),rainPos=new Float32Array(600*6);
  for(let i=0;i<600;i++){const x=(random()-.5)*600,y=(random()-.5)*600,z=(random()-.5)*600;rainPos.set([x,y,z,x-1,y+12,z],i*6);}
  rainG.setAttribute('position',new THREE.BufferAttribute(rainPos,3));this.rain=new THREE.LineSegments(rainG,new THREE.LineBasicMaterial({color:'#d5e6ef',transparent:true,opacity:.32,depthWrite:false}));this.rain.visible=false;this.scene.add(this.rain);
  const snowG=new THREE.BufferGeometry(),snowPos=new Float32Array(450*3);for(let i=0;i<snowPos.length;i++)snowPos[i]=(random()-.5)*600;snowG.setAttribute('position',new THREE.BufferAttribute(snowPos,3));this.snow=new THREE.Points(snowG,new THREE.PointsMaterial({color:'#fffafa',size:2.2,transparent:true,opacity:.65,depthWrite:false}));this.snow.visible=false;this.scene.add(this.snow);
  const starGeometry=new THREE.BufferGeometry(),starPositions=new Float32Array(1200*3);for(let i=0;i<1200;i++){const angle=random()*Math.PI*2,elevation=.12+random()*1.4;starPositions.set([Math.cos(angle)*Math.cos(elevation)*28000,Math.sin(elevation)*28000,Math.sin(angle)*Math.cos(elevation)*28000],i*3);}starGeometry.setAttribute('position',new THREE.BufferAttribute(starPositions,3));this.stars=new THREE.Points(starGeometry,new THREE.PointsMaterial({color:'#fff2dc',size:22,transparent:true,opacity:0,depthWrite:false,fog:false}));this.scene.add(this.stars);this.moon=new THREE.Mesh(new THREE.SphereGeometry(280,24,16),new THREE.MeshBasicMaterial({color:'#fff2d2',fog:false}));this.moon.position.set(-18000,12500,-14000);this.moon.visible=false;this.scene.add(this.moon);
  this.scene.add(this.aircraft);this.ready=this.loadModels();
 }
 createTerrain(){
  const verts:number[]=[],colors:number[]=[];const step=65;const col=new THREE.Color();
  for(let z=-12000;z<14500;z+=step)for(let x=-6500;x<7300;x+=step){if(!isLand(x+step/2,z+step/2))continue;const corners=[[x,z],[x+step,z],[x,z+step],[x+step,z+step]];for(const index of [0,2,1,1,2,3]){const[a,b]=corners[index];const h=terrainHeight(a,b);verts.push(a,h,b);col.set(h>600?'#819886':h>260?'#719777':h>80?'#8baa7e':'#adc295');col.offsetHSL(0,0,Math.sin(a*.015+b*.013)*.025);colors.push(col.r,col.g,col.b);}}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const smooth=mergeVertices(geometry);smooth.computeVertexNormals();this.scene.add(new THREE.Mesh(smooth,new THREE.MeshLambertMaterial({vertexColors:true})));
  // Fine shoreline foundations preserve Natural Earth's coastline under the terrain grid.
  for(const p of polygons){if(p.length<4)continue;const shape=new THREE.Shape(p.map(v=>new THREE.Vector2(v[0],-v[1])));const base=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshLambertMaterial({color:'#b7c7a0'}));base.rotation.x=-Math.PI/2;base.position.y=1;this.scene.add(base);}
 }
 createCities(){
  const random=rng(1024),dummy=new THREE.Object3D(),color=new THREE.Color();const items:{x:number;y:number;z:number;w:number;h:number;d:number;c:string}[]=[];
  cities.forEach((c,ci)=>{const center=positions[ci];const count=ci===0?580:ci===6?460:ci===1?320:170;const occupied=new Set<string>();
   for(let i=0;i<count;i++){const x=center.x+(random()-.5)*650,z=center.z+(random()-.5)*550;if(!isLand(x,z))continue;const gx=Math.round((x-center.x)/32)*32+center.x,gz=Math.round((z-center.z)/32)*32+center.z;const cell=`${gx},${gz}`;if(occupied.has(cell)||!isLand(gx,gz))continue;occupied.add(cell);const w=11+random()*13,d=11+random()*13,h=(12+random()**3*(ci===0||ci===6?145:65));const y=terrainHeight(gx,gz);items.push({x:gx,y,z:gz,w,h,d,c:c.color});this.obstacles.push({x:gx,z:gz,w:w/2,d:d/2,h:y+h});}
   const roadMat=new THREE.MeshLambertMaterial({color:'#bbc3b8'});for(let n=-4;n<=4;n++){const x=center.x+n*63,z=center.z;const road=new THREE.Mesh(new THREE.BoxGeometry(8,1,570),roadMat);road.position.set(x,terrainHeight(x,z)+1,z);this.scene.add(road);const cross=new THREE.Mesh(new THREE.BoxGeometry(560,1,7),roadMat);cross.position.set(center.x,terrainHeight(center.x,center.z+n*63)+1,center.z+n*63);this.scene.add(cross);}
  });
  const canvas=document.createElement('canvas');canvas.width=64;canvas.height=128;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#e8ece9';ctx.fillRect(0,0,64,128);for(let y=7;y<128;y+=12)for(let x=6;x<64;x+=13){ctx.fillStyle=y%3?'#6b929a':'#c3d5d0';ctx.fillRect(x,y,5,6);}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;
  const glow=document.createElement('canvas');glow.width=64;glow.height=128;const gc=glow.getContext('2d')!;gc.fillStyle='black';gc.fillRect(0,0,64,128);gc.fillStyle='#ffd58d';for(let y=7;y<128;y+=12)for(let x=6;x<64;x+=13)if(random()>.35)gc.fillRect(x,y,5,6);const emissiveMap=new THREE.CanvasTexture(glow);emissiveMap.colorSpace=THREE.SRGBColorSpace;this.cityMaterial=new THREE.MeshLambertMaterial({map:texture,emissiveMap,emissive:'#fff1bf',emissiveIntensity:0});const buildings=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),this.cityMaterial,items.length);items.forEach((o,i)=>{dummy.position.set(o.x,o.y+o.h/2,o.z);dummy.scale.set(o.w,o.h,o.d);dummy.updateMatrix();buildings.setMatrixAt(i,dummy.matrix);color.set(o.c);buildings.setColorAt(i,color);});this.scene.add(buildings);
  // Stylized Han River ribbon through the Seoul area.
  const s=positions[0],river=new THREE.CatmullRomCurve3([new THREE.Vector3(s.x-950,13,s.z+140),new THREE.Vector3(s.x-420,13,s.z+270),new THREE.Vector3(s.x+180,13,s.z+300),new THREE.Vector3(s.x+650,13,s.z+100)]);const riverMesh=new THREE.Mesh(new THREE.TubeGeometry(river,64,43,5,false),new THREE.MeshLambertMaterial({color:'#74afb8'}));riverMesh.scale.y=.18;this.scene.add(riverMesh);riverMesh.position.y=22;
 }
 createTrees(){const random=rng(765),dummy=new THREE.Object3D(),trees:{x:number;y:number;z:number;s:number}[]=[];for(let i=0;i<12500;i++){const x=(random()-.5)*12500,z=(random()-.25)*18000;if(!isLand(x,z)||positions.some(p=>Math.hypot(p.x-x,p.z-z)<330))continue;trees.push({x,z,y:terrainHeight(x,z),s:6+random()*17});}
  const mesh=new THREE.InstancedMesh(new THREE.ConeGeometry(1,2.8,5),new THREE.MeshLambertMaterial({color:'#527d68'}),trees.length);trees.forEach((t,i)=>{dummy.position.set(t.x,t.y+t.s,t.z);dummy.scale.set(t.s*.65,t.s,t.s*.65);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,new THREE.Color().setHSL(.36+random()*.04,.2,.32+random()*.12));});this.scene.add(mesh);}
 box(group:THREE.Group,x:number,y:number,z:number,w:number,h:number,d:number,color:string){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshLambertMaterial({color}));mesh.position.set(x,y,z);group.add(mesh);return mesh;}
 bridge(center:THREE.Vector3,length:number,color:string){const g=new THREE.Group();g.position.copy(center);this.box(g,0,37,0,length,5,22,'#dadcca');for(const x of [-length*.3,length*.3]){for(const z of [-14,14])this.box(g,x,65,z,6,128,6,color);this.box(g,x,115,0,9,6,34,color);}for(const z of [-14,14]){const points=[];for(let i=0;i<=40;i++){const x=-length*.3+length*.6*i/40;points.push(new THREE.Vector3(x,55+65*((i-20)/20)**2,z));if(i%2===0)this.box(g,x,(points.at(-1)!.y+38)/2,z,1,points.at(-1)!.y-38,1,'#ececdb');}const cable=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),40,1.4,4,false),new THREE.MeshLambertMaterial({color:'#f5f0d8'}));g.add(cable);}this.scene.add(g);return g;}
 createLandmarks(){cities.forEach((c,i)=>{const p=positions[i];const g=new THREE.Group();g.position.set(p.x+120,terrainHeight(p.x+120,p.z-100),p.z-100);this.landmarks.push(g);this.scene.add(g);});
 const bridges=[{i:1,x:-360,z:170,l:820,c:'#e6e9dd'},{i:4,x:100,z:240,l:430,c:'#cd6954'},{i:6,x:230,z:210,l:750,c:'#f1eee0'}];for(const b of bridges){const p=positions[b.i];this.bridge(new THREE.Vector3(p.x+b.x,0,p.z+b.z),b.l,b.c);this.landmarks[b.i].position.set(p.x+b.x,45,p.z+b.z);}
 for(const ci of [1,3,4,5,6,7]){const p=positions[ci];for(let j=0;j<11;j++){const x=p.x-360+j*62,z=p.z+330;if(isLand(x,z))continue;const boat=new THREE.Group();boat.position.set(x,1,z);boat.rotation.y=j*.7;const hull=new THREE.Mesh(new THREE.CapsuleGeometry(3,16,3,8),new THREE.MeshLambertMaterial({color:j%2?'#d3a66a':'#e9ebe1'}));hull.rotation.x=Math.PI/2;hull.scale.y=.7;boat.add(hull);this.box(boat,0,3,1,5,4,7,'#f2efe3');this.box(boat,0,7,2,.5,8,.5,'#555d60');this.scene.add(boat);}}
 // Coastal turbines and harbor boats give the quieter coast its own silhouette.
 [2,3,5,7].forEach(i=>{const p=positions[i];for(let j=0;j<8;j++){const g=new THREE.Group();g.position.set(p.x+(j-3)*80,terrainHeight(p.x+(j-3)*80,p.z+290),p.z+290);this.box(g,0,35,0,3,70,3,'#f5f1df');for(let b=0;b<3;b++){const blade=this.box(g,0,80,0,3,45,1,'#f5f1df');blade.position.set(Math.sin(b*Math.PI*2/3)*20,70+Math.cos(b*Math.PI*2/3)*20,0);blade.rotation.z=-b*Math.PI*2/3;}this.scene.add(g);}});
 }
 async loadModels(){const loader=new GLTFLoader();const base=import.meta.env.BASE_URL;const plane=await loader.loadAsync(base+'models/glider.glb');this.aircraft.add(plane.scene);this.aircraft.scale.setScalar(1.9);const load=async(file:string,indexes:number[])=>{const data=await loader.loadAsync(base+'models/'+file+'.glb');for(const i of indexes)this.landmarks[i].add(data.scene.clone());};await Promise.all([load('namsan',[0]),load('pavilion',[3,5,8]),load('lighthouse',[2,7,9])]);}
 ground(x:number,z:number){let y=terrainHeight(x,z);for(const o of this.obstacles)if(Math.abs(x-o.x)<o.w+16&&Math.abs(z-o.z)<o.d+16)y=Math.max(y,o.h);const tower=this.landmarks[0].position;if(Math.hypot(x-tower.x,z-tower.z)<50)y=Math.max(y,tower.y+220);return y;}
 update(dt:number,weather:{cloud:number;wind:number;direction:number;day:boolean;code:number},position:THREE.Vector3){this.time+=dt;const t=this.time;(this.ocean.material as THREE.ShaderMaterial).uniforms.time.value=t;const night=!weather.day;const overcast=weather.cloud/100;(this.stars.material as THREE.PointsMaterial).opacity=THREE.MathUtils.damp((this.stars.material as THREE.PointsMaterial).opacity,night?1-overcast:0,1,dt);this.moon.visible=night;const fog=this.scene.fog as THREE.FogExp2;this.fogBase=THREE.MathUtils.lerp(this.fogBase,(night?.00015:.00008)+overcast*.000065,dt);fog.density=this.fogBase;fog.color.lerp(new THREE.Color(night?'#263d56':overcast>.75?'#a2b8c4':'#aed1df'),dt);
 this.hemi.intensity=THREE.MathUtils.lerp(this.hemi.intensity,night?.55:2.0-overcast*.4,dt);this.sun.intensity=THREE.MathUtils.lerp(this.sun.intensity,night?.12:2.7-overcast*1.8,dt);(this.ocean.material as THREE.ShaderMaterial).uniforms.light.value=night?.35:1;
 const sun=new THREE.Vector3().setFromSphericalCoords(1,THREE.MathUtils.degToRad(night?94:65),THREE.MathUtils.degToRad(235));this.sky.material.uniforms.sunPosition.value.copy(sun);this.sky.material.uniforms.turbidity.value=3+overcast*7;this.sky.material.uniforms.rayleigh.value=night?.4:1.5;
 if(this.cityMaterial)this.cityMaterial.emissiveIntensity=THREE.MathUtils.damp(this.cityMaterial.emissiveIntensity,night?1.5:0,1,dt);
 (this.ocean.material as THREE.ShaderMaterial).uniforms.haze.value.copy(fog.color);
 const mist=this.clouds.update(dt,weather,position);fog.density+=mist*.0013;
 const snowing=[71,73,75,77,85,86].includes(weather.code);
 this.rain.visible=weather.code>=51&&!snowing&&position.y<1600;this.snow.visible=snowing&&position.y<1600;
 if(this.rain.visible){this.rain.position.copy(position);const a=this.rain.geometry.attributes.position;for(let i=0;i<a.count;i+=2){let y=a.getY(i)-dt*190;if(y< -300)y+=600;a.setY(i,y);a.setY(i+1,y+12);}a.needsUpdate=true;}
 if(this.snow.visible){this.snow.position.copy(position);const a=this.snow.geometry.attributes.position;for(let i=0;i<a.count;i++){let y=a.getY(i)-dt*20;if(y< -300)y+=600;a.setY(i,y);}a.needsUpdate=true;}

 }
}
